#!/usr/bin/bash
(cd vendor/zxing/cpp && /Developer42p/usr/bin/clang++ -o build/core/src/zxing/qrcode/detector/da.o -c -O0 -fPIC -Ibuild/core/src build/core/src/zxing/qrcode/detector/da.cpp)
(cd vendor/zxing/cpp && /Developer42p/usr/bin/clang++ -o build/core/src/zxing/qrcode/detector/db.o -c -O0 -fPIC -Ibuild/core/src build/core/src/zxing/qrcode/detector/db.cpp)
rm -f vendor/zxing/cpp/build/libzxing.a lib/zxing/zxing.bundle && rake zxing:test[qrcode-1]
rm -f vendor/zxing/cpp/build/libzxing.a lib/zxing/zxing.bundle && rake zxing:test[qrcode-1] 2>&1 | tee good

exit

(cd vendor/zxing/cpp && /Developer42p/usr/bin/clang++ -o build/core/src/zxing/qrcode/detector/da.o -c -O1 -fPIC -Ibuild/core/src build/core/src/zxing/qrcode/detector/da.cpp)
(cd vendor/zxing/cpp && /Developer42p/usr/bin/clang++ -o build/core/src/zxing/qrcode/detector/db.o -c -O0 -fPIC -Ibuild/core/src build/core/src/zxing/qrcode/detector/db.cpp)
rm -f vendor/zxing/cpp/build/libzxing.a lib/zxing/zxing.bundle && rake zxing:test[qrcode-1]
rm -f vendor/zxing/cpp/build/libzxing.a lib/zxing/zxing.bundle && rake zxing:test[qrcode-1] 2>&1 | tee bad

diff good bad